version: "3"
services:
  app:
    build: .
    ports:
      - 8000:8000
  redis-db:
    image: redis:alpine
  mysql-db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root