version: "3"
services:

  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mysql-db
      - redis-db

  redis-db:
    image: redis:alpine

  mysql-db:
    image: mysql
    volumes:
      - ./starter.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
